// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TailorCV.CVGenerator.Infrastructure;

#nullable disable

namespace TailorCV.CVGenerator.Infrastructure.Migrations
{
    [DbContext(typeof(CVGeneratorDbContext))]
    [Migration("20260513064506_ConvertEnumsToString")]
    partial class ConvertEnumsToString
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("cvgenerator")
                .HasAnnotation("ProductVersion", "10.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TailorCV.CVGenerator.Domain.GeneratedCV", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .HasColumnType("jsonb")
                        .HasColumnName("content");

                    b.Property<string>("CoverLetter")
                        .HasColumnType("text")
                        .HasColumnName("cover_letter");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Error")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("error");

                    b.Property<string>("GenerationType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("generation_type");

                    b.Property<string>("JobSnapshot")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("job_snapshot");

                    b.Property<string>("MatchScore")
                        .HasColumnType("jsonb")
                        .HasColumnName("match_score");

                    b.Property<string>("PdfKey")
                        .HasColumnType("text")
                        .HasColumnName("pdf_key");

                    b.Property<string>("PdfStatus")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("pdf_status");

                    b.Property<string>("ProfileSnapshot")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("profile_snapshot");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("TailoringPrompt")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("tailoring_prompt");

                    b.Property<Guid>("TemplateId")
                        .HasColumnType("uuid")
                        .HasColumnName("template_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_generated_cvs");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_generated_cvs_created_at");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_generated_cvs_status");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_generated_cvs_user_id");

                    b.ToTable("generated_cvs", "cvgenerator");
                });
#pragma warning restore 612, 618
        }
    }
}
