// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TailorCV.JobScraper.Infrastructure;

#nullable disable

namespace TailorCV.JobScraper.Migrations
{
    [DbContext(typeof(JobScraperDbContext))]
    [Migration("20260418011614_JobScraperInitialCreate")]
    partial class JobScraperInitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TailorCV.JobScraper.Domain.JobDescription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Company")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("company");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Label")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("label");

                    b.Property<string>("Location")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("location");

                    b.PrimitiveCollection<List<string>>("Qualifications")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("qualifications");

                    b.Property<string>("RawText")
                        .HasMaxLength(10000)
                        .HasColumnType("character varying(10000)")
                        .HasColumnName("raw_text");

                    b.PrimitiveCollection<List<string>>("RequiredSkills")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("required_skills");

                    b.PrimitiveCollection<List<string>>("Responsibilities")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("responsibilities");

                    b.Property<string>("SeniorityLevel")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("seniority_level");

                    b.Property<string>("SourceUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("source_url");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_job_descriptions");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_job_descriptions_user_id");

                    b.ToTable("job_descriptions", "jobscraper");
                });

            modelBuilder.Entity("TailorCV.JobScraper.Domain.ParseJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Error")
                        .HasColumnType("text")
                        .HasColumnName("error");

                    b.Property<string>("RawInput")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("raw_input");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "ParsedData", "TailorCV.JobScraper.Domain.ParseJob.ParsedData#ParsedJobData", b1 =>
                        {
                            b1.Property<string>("Company");

                            b1.Property<string>("Location");

                            b1.PrimitiveCollection<string>("Qualifications")
                                .IsRequired();

                            b1.PrimitiveCollection<string>("RequiredSkills")
                                .IsRequired();

                            b1.PrimitiveCollection<string>("Responsibilities")
                                .IsRequired();

                            b1.Property<string>("SeniorityLevel")
                                .IsRequired();

                            b1.Property<string>("Title")
                                .IsRequired();

                            b1
                                .ToJson("parsed_data")
                                .HasColumnType("jsonb");
                        });

                    b.HasKey("Id")
                        .HasName("pk_parse_jobs");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_parse_jobs_status");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_parse_jobs_user_id");

                    b.ToTable("parse_jobs", "jobscraper");
                });
#pragma warning restore 612, 618
        }
    }
}
