// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TailorCV.Profile.Domain;
using TailorCV.Profile.Infrastructure;

#nullable disable

namespace TailorCV.Profile.Infrastructure.Migrations
{
    [DbContext(typeof(ProfileDbContext))]
    [Migration("20260426145850_JsonBSections")]
    partial class JsonBSections
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("profile")
                .HasAnnotation("ProductVersion", "10.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TailorCV.Profile.Domain.ParseJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Error")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("error");

                    b.Property<string>("S3Key")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("s3key");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "ParsedData", "TailorCV.Profile.Domain.ParseJob.ParsedData#ParsedResumeData", b1 =>
                        {
                            b1.Property<string>("Github");

                            b1.Property<string>("Headline");

                            b1.Property<string>("Linkedin");

                            b1.Property<string>("Location");

                            b1.Property<string>("Phone");

                            b1.Property<string>("Summary");

                            b1.Property<string>("Website");

                            b1.ComplexCollection(typeof(List<Dictionary<string, object>>), "Sections", "TailorCV.Profile.Domain.ParseJob.ParsedData#ParsedResumeData.Sections#ParsedSection", b2 =>
                                {
                                    b2.IsRequired();

                                    b2.Property<int>("Order");

                                    b2.Property<string>("Type")
                                        .IsRequired();

                                    b2.ComplexCollection(typeof(List<Dictionary<string, object>>), "Items", "TailorCV.Profile.Domain.ParseJob.ParsedData#ParsedResumeData.Sections#ParsedSection.Items#ParsedItem", b3 =>
                                        {
                                            b3.IsRequired();

                                            b3.Property<string>("Category");

                                            b3.Property<string>("Company");

                                            b3.Property<string>("Date");

                                            b3.Property<string>("Degree");

                                            b3.Property<string>("Description");

                                            b3.Property<string>("EndDate");

                                            b3.Property<string>("ExpiryDate");

                                            b3.Property<string>("Field");

                                            b3.Property<string>("Gpa");

                                            b3.Property<string>("Institution");

                                            b3.Property<bool?>("IsCurrent");

                                            b3.Property<string>("Issuer");

                                            b3.Property<string>("LanguageName");

                                            b3.Property<string>("Name");

                                            b3.Property<int>("Order");

                                            b3.Property<string>("Proficiency");

                                            b3.Property<string>("Role");

                                            b3.PrimitiveCollection<string>("SkillItems");

                                            b3.Property<string>("StartDate");

                                            b3.Property<string>("Subtitle");

                                            b3.PrimitiveCollection<string>("TechStack");

                                            b3.Property<string>("Title");

                                            b3.Property<string>("Url");
                                        });
                                });

                            b1
                                .ToJson("parsed_data")
                                .HasColumnType("jsonb");
                        });

                    b.HasKey("Id")
                        .HasName("pk_parse_jobs");

                    b.ToTable("parse_jobs", "profile");
                });

            modelBuilder.Entity("TailorCV.Profile.Domain.Profile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("GithubUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("github_url");

                    b.Property<string>("Headline")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("headline");

                    b.Property<bool>("IsShared")
                        .HasColumnType("boolean")
                        .HasColumnName("is_shared");

                    b.Property<string>("LinkedinUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("linkedin_url");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("location");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("phone");

                    b.Property<List<ProfileSection>>("Sections")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("sections");

                    b.Property<string>("ShareId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("share_id");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("summary");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("Website")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("website");

                    b.HasKey("Id")
                        .HasName("pk_profiles");

                    b.HasIndex("ShareId")
                        .IsUnique()
                        .HasDatabaseName("ix_profiles_share_id")
                        .HasFilter("\"share_id\" IS NOT NULL");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_profiles_user_id");

                    b.ToTable("profiles", "profile");
                });
#pragma warning restore 612, 618
        }
    }
}
