<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\..\..\TailorCV.Shared\TailorCV.Shared.csproj" />
    <ProjectReference Include="..\TailorCV.CVGenerator.Contracts\TailorCV.CVGenerator.Contracts.csproj" />
    <ProjectReference Include="..\..\Profile\TailorCV.Profile.Contracts\TailorCV.Profile.Contracts.csproj" />
    <ProjectReference Include="..\..\JobDescriptions\TailorCV.JobDescriptions.Contracts\TailorCV.JobDescriptions.Contracts.csproj" />
    <ProjectReference Include="..\..\Templates\TailorCV.Templates.Contracts\TailorCV.Templates.Contracts.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Grpc.AspNetCore" />
    <PackageReference Include="Grpc.Net.Client" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="WolverineFx" />
    <PackageReference Include="WolverineFx.RabbitMQ" />
  </ItemGroup>

</Project>
