<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\..\..\TailorCV.Shared\TailorCV.Shared.csproj" />
    <ProjectReference Include="..\TailorCV.CVGenerator.Contracts\TailorCV.CVGenerator.Contracts.csproj" />
    <ProjectReference Include="..\..\Profile\TailorCV.Profile.Contracts\TailorCV.Profile.Contracts.csproj" />
    <ProjectReference Include="..\..\JobScraper\TailorCV.JobScraper.Contracts\TailorCV.JobScraper.Contracts.csproj" />
    <ProjectReference Include="..\..\Templates\TailorCV.Templates.Contracts\TailorCV.Templates.Contracts.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="EFCore.NamingConventions" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" />
    <PackageReference Include="Grpc.Net.Client" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
    <PackageReference Include="OpenAI" />
    <PackageReference Include="PuppeteerSharp" />
    <PackageReference Include="WolverineFx" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
