<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\TailorCV.JobDescriptions.Contracts\TailorCV.JobDescriptions.Contracts.csproj" />
    <ProjectReference Include="..\..\..\TailorCV.Shared\TailorCV.Shared.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Playwright" />
    <PackageReference Include="OpenAI" />
    <PackageReference Include="Serilog.AspNetCore" />
    <PackageReference Include="WolverineFx" />
    <PackageReference Include="WolverineFx.RabbitMQ" />
  </ItemGroup>

</Project>