<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\..\..\TailorCV.Shared\TailorCV.Shared.csproj" />
    <ProjectReference Include="..\TailorCV.Templates.Contracts\TailorCV.Templates.Contracts.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Grpc.AspNetCore" />
  </ItemGroup>

</Project>
