<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
    <NoWarn>IDE0008;CA1861;CA1847;CA2000</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" />
    <PackageReference Include="FluentAssertions" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\TailorCV.Api\TailorCV.Api.csproj" />
    <ProjectReference Include="..\..\src\TailorCV.Infrastructure\TailorCV.Infrastructure.csproj" />
    <ProjectReference Include="..\..\src\TailorCV.SharedKernel\TailorCV.SharedKernel.csproj" />
    <ProjectReference Include="..\..\src\Modules\TailorCV.Modules.Identity\TailorCV.Modules.Identity.csproj" />
  </ItemGroup>

</Project>