<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\..\..\TailorCV.Shared\TailorCV.Shared.csproj" />
    <ProjectReference Include="..\..\..\TailorCV.Infrastructure\TailorCV.Infrastructure.csproj" />
    <ProjectReference Include="..\TailorCV.Profile.Contracts\TailorCV.Profile.Contracts.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Serilog.AspNetCore" />
    <PackageReference Include="WolverineFx" />
    <PackageReference Include="WolverineFx.RabbitMQ" />
  </ItemGroup>

</Project>
